version: '3.1'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://localhost:27017/mindy
    networks:
      - mongo-compose-network

  db:
    container_name: db
    image: mongo:4.4
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
